---
- hosts: toolserver
  become: true
  become_method: sudo
  vars: 
    AWS_ACCESS_KEY_ID: 
    POSTGRES_HOST: 
    POSTGRES_PASSWORD: 
    AWS_SECRET_ACCESS_KEY: 

  tasks:

    - name: Install git
      yum:
        name: "{{item}}"
        state: present
        update_cache: yes

    - name: install docker
      yum:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
       # - ca-certificates
        - docker

    - name: start and enable docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add docker user to a super user
      command: usermod -aG docker $USER

    - name: restart docker
      service: 
        name: docker 
        state: restarted
 

    - name: Install Docker Module for Python
      pip:
      yum:
        name: "{{item}}"
        state: present 

- name: Build, push, and run Docker image
  hosts: your_target_host
  tasks:
    - name: Build Docker image
      ansible.builtin.docker_image:
        name: kitskat/hrapp:v01
        path: /c/Users/user/Downloads/Toolserver03
        state: present

    - name: Log in to Docker Hub
      ansible.builtin.docker_login:
        username: your_dockerhub_username
        password: your_dockerhub_password

    - name: Push Docker image to Docker Hub
      ansible.builtin.docker_image:
        name: kitskat/hrapp:v01
        push: yes

    - name: Run Docker container
      ansible.builtin.docker_container:
        name: hrapp_container
        image: kitskat/hrapp:v01
        state: started
        ports:
          - "8080:80"

# Push To Github

  hosts: toolserver
  tasks:
  
    - name: Log in to GitHub Container Registry
      ansible.builtin.docker_login:
        registry_url: ghcr.io
        username: your-github-username
        password: your_github_token

    - name: Push Docker image to GitHub Container Registry
      ansible.builtin.docker_image:
        name: ghcr.io/your-github-username/hrapp:v01
        push: yes



